export const QUERY_KEYS = {
  login: "login",
  orders: "orders",
  products: "products",
  users: "users",
  userByIds: "userByIds",
  subcategoryByIds: "subcategoryByIds",
  newProduct: "newProduct",
  categories: "categories",
  subcategories: "subcategories",
  editProductById: "editProductById",
  getProductById: "getProductById",
  deleteProductById: "deleteProductById",
  editProductsByIds: "editProductsByIds",
};
